import './UsedEPin.css';
import { epinRows } from './epinMockData';

const usedRows = epinRows.filter((row) => row.status === 'Used');

function UsedEPin() {
  return (
    <div>
      <h1 className="page-title">Used ePin</h1>

      <div className="panel">
        <div className="epin-header-row">
          <h2 className="epin-title">List ePin - Used</h2>
        </div>

        <div className="epin-filter-grid">
          <input className="text-input" placeholder="ePin" />
          <select className="select-input">
            <option>ePin Name</option>
            <option>Activation</option>
          </select>
          <input className="text-input" placeholder="Generated By" />
          <input className="text-input" placeholder="Current Owner" />
          <input className="text-input" type="date" />
          <input className="text-input" type="date" />
          <button className="btn-primary">Search</button>
        </div>

        <div className="table-wrap">
          <table className="data-table">
            <thead>
              <tr>
                <th>#</th>
                <th>ePinName</th>
                <th>ePin</th>
                <th>Cost</th>
                <th>Gen. Date</th>
                <th>Gen. By</th>
                <th>Cur.Owner</th>
                <th>Status</th>
                <th>Used By</th>
                <th>Used Date</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              {usedRows.map((row) => (
                <tr key={row.id}>
                  <td>{row.id}</td>
                  <td>{row.epinName}</td>
                  <td>{row.epin}</td>
                  <td>{row.cost}</td>
                  <td>{row.genDate}</td>
                  <td>{row.genBy}</td>
                  <td>{row.currentOwner}</td>
                  <td>
                    <span className="epin-chip epin-chip-used">{row.status}</span>
                  </td>
                  <td>{row.usedBy}</td>
                  <td>{row.usedDate}</td>
                  <td>-</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <div className="table-footer">
          <span>Showing Page 1 of 7 From 65 Rows</span>
          <div className="pagination">
            <button className="page-btn">&lt;&lt;</button>
            <button className="page-btn">&lt;</button>
            <button className="page-btn active">1</button>
            <button className="page-btn">2</button>
            <button className="page-btn">3</button>
            <button className="page-btn">&gt;</button>
            <button className="page-btn">&gt;&gt;</button>
          </div>
        </div>
      </div>
    </div>
  );
}

export default UsedEPin;
